# -*- coding: utf-8 -*-
"""data_cleaning_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wB_2JVKDTVURdXFa3IwbULPQiIu6RBoO
"""

import numpy as np
import pandas as pd    #import of requires libraries in python.

df_data = pd.read_csv("/content/netflix_titles.csv")   #read csv file
df_data.head()    #display of first 5 rows of the data set.

df_data.isnull().sum()       #gives the sum of all null values in each column.

#replacing NaN in few columns because the missing values are too large to just drop the rows.
df_data.fillna({'director':'Not Specified'},inplace=True)  #replace NaN in director column with Not Specified.

df_data.fillna({'cast':'Not Specified'},inplace=True)  #replace NaN in cast column with Not Specified.

df_data.fillna({'country':'Not Specified'},inplace=True)  #replace NaN in country column with Not Specified.

#removing some rows with few missing values.
df_data.dropna(inplace=True)

df_data.isnull().sum()

df_data.info()

# changing data_added datatype to datetime.
df_data['date_added'] = pd.to_datetime(df_data['date_added'], format='%d,%b,%Y')

df_data.info()  #this shows the datatype of 'data_added' changed to datetime64.

# The .str.split() method separates the string by the space.
# 'expand=True' creates new columns for the split parts.
duration_split = df_data['duration'].str.split(' ', expand=True)

# Assign the new split columns to the DataFrame
df_data['duration_value'] = pd.to_numeric(duration_split[0]) # The number part
df_data['duration_unit'] = duration_split[1] # The unit part ('min' or 'Season(s)')

# Drop the original 'duration' column as it's no longer needed
df_data.drop(columns=['duration'], inplace=True)

#  Removing Duplicates
df_data.drop_duplicates(inplace=True)


# This is your main deliverable
df_data.to_csv('netflix_cleaned.csv', index=False)